execute as @a[hasitem={location=slot.weapon.mainhand,item=diamond_pickaxe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=diamond_pickaxe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=golden_pickaxe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=golden_pickaxe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=iron_pickaxe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=iron_pickaxe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=netherite_pickaxe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=netherite_pickaxe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=stone_pickaxe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=stone_pickaxe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=wooden_pickaxe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=wooden_pickaxe}]

execute as @a[hasitem={location=slot.weapon.mainhand,item=diamond_axe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=diamond_axe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=golden_axe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=golden_axe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=iron_axe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=iron_axe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=netherite_axe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=netherite_axe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=stone_axe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=stone_axe}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=wooden_axe}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=wooden_axe}]

execute as @a[hasitem={location=slot.weapon.mainhand,item=diamond_shovel}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=diamond_shovel}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=golden_shovel}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=golden_shovel}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=iron_shovel}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=iron_shovel}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=netherite_shovel}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=netherite_shovel}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=stone_shovel}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=stone_shovel}]
execute as @a[hasitem={location=slot.weapon.mainhand,item=wooden_shovel}] at @s as @e[type=item,r=30] at @s run tp ^ ^ ^0.2 facing @p[hasitem={location=slot.weapon.mainhand,item=wooden_shovel}]